name: WindSpigot PR Build

on:
  pull_request:

jobs:
  cleanup-and-build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip]')"
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17
        server-id: github
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean package --file pom.xml
